myshop/cart/urls.py
from django.urls import path

from .views import cart_remove, cart_add, cart_detail

app_name = "cart"

urlpatterns = [
    path("", cart_detail, name="cart_detail"),
    path(
        "add/<int:product_pk>",
        cart_add,
        name="cart_add",
    ),
    path(
        "remove/<int:product_pk>",
        cart_remove,
        name="cart_remove",
    ),
]

myshop/myauth/urls.py
from django.urls import path

from .views import (
    MyauthLoginView,
    MyauthRegistrationView,
    MyauthRegistrationDoneView,
    MyauthLogoutView,
    MyauthPasswordChangeView,
    MyauthPasswordChangeDoneView,
    MyauthRegistrationActivateView,
    MyauthRegistrationActivationDoneView,
)

app_name = "myauth"
urlpatterns = [
    path("registration/", MyauthRegistrationView.as_view(), name="registration"),
    path(
        "registration_activate/<str:key>/<str:confirm>/",
        MyauthRegistrationActivateView.as_view(),
        name="registration_activate",
    ),
    path(
        "registration_activation_done/",
        MyauthRegistrationActivationDoneView.as_view(),
        name="registration_activation_done",
    ),
    path(
        "registration_done/",
        MyauthRegistrationDoneView.as_view(),
        name="registration_done",
    ),
    path("login/", MyauthLoginView.as_view(), name="login"),
    path("logout/", MyauthLogoutView.as_view(), name="logout"),
    path(
        "password_change/", MyauthPasswordChangeView.as_view(), name="password_change"
    ),
    path(
        "password_change_done/",
        MyauthPasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
]

myshop/myshop/urls.py
import pkgutil

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("cart/", include("cart.urls")),
    path("order/", include("order.urls")),
    path("myauth/", include("myauth.urls")),
    path("", include("products.urls")),
]

if settings.DEBUG and pkgutil.find_loader("debug_toolbar"):
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  <script defer src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
  <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
  {% block head %}
  
  {% endblock %}
  <title>
    {% block title %}
    {% endblock %}
  </title>
</head>
<body>
{% include "nav.html" %}
{% block container %}
{% endblock %}
</body>
</html>

myshop/templates/empty.html
{% load i18n %}
{% get_current_language as LANG %}

<!DOCTYPE html>
<html lang="{{ LANG }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
      {% block title %}

      {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
</head>
<body>
<div class="container">
    {% block container %}
    {% endblock %}
</div>
</body>
</html>

myshop/templates/nav.html
{% load static %}
{% load bootstrap_icons %}

<nav class="navbar navbar-expand-lg navbar-light bg-light navbar-fixed-top mb-2">
  <div class="container">
    <a class="navbar-brand" href="/">
      <img src="{% static 'img/logo.png' %}" alt="{% static 'img/no-image.png' %}" width="40" height="40">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item me-auto">
          <a href="{% url "cart:cart_detail" %}">
            <div class="d-flex flex-column align-items-center">
              {% with total_items=cart|length %}
              <a
                class="{% if total_items == 0 %} mt-1 {% endif %}"
                href="{% url "cart:cart_detail" %}"
              >
                {% bs_icon 'cart4' color='red' size='2rem' %}
              </a>
                  {% if total_items > 0 %}
                    <small class="text-muted">
                      ({{ total_items }} item{{ total_items|pluralize }},
                      ${{ cart.get_total_price }})
                    </small>
                  {% endif %}
              {% endwith %}
            </div>
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
             data-bs-toggle="dropdown" aria-expanded="false">
            {% bs_icon 'gear' size='2rem' %}
            Account
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
              {% if user %}
                <a class="dropdown-item" href="#">
                    {% bs_icon 'person' %}
                    {{ user }}
                </a>
              {% else %}
                <a class="dropdown-item" href="{% url "myauth:login" %}">
                    Login
                </a>
              {% endif %}
            </li>
            {% if not user %}
              <li>
                <a class="dropdown-item" href="{% url "myauth:registration" %}">
                    Create an account
                </a>
              </li>
            {% endif %}
            <li>
              <hr class="dropdown-divider">
            </li>
            <li>
              <a class="dropdown-item" href="{% url "myauth:password_change" %}">
                Change password
              </a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url "myauth:logout" %}">
                {% bs_icon 'box-arrow-left' %}
                Logout
              </a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>