myshop/cart/urls.py
from django.urls import path

from .views import cart_remove, cart_add, cart_detail

app_name = "cart"

urlpatterns = [
    path("", cart_detail, name="cart_detail"),
    path(
        "add/<int:product_pk>",
        cart_add,
        name="cart_add",
    ),
    path(
        "remove/<int:product_pk>",
        cart_remove,
        name="cart_remove",
    ),
]

myshop/myshop/urls.py
import pkgutil

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("cart/", include("cart.urls")),
    path("order/", include("order.urls")),
    path("myauth/", include("myauth.urls")),
    path("", include("products.urls")),
]

if settings.DEBUG and pkgutil.find_loader("debug_toolbar"):
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/order/urls.py
from django.urls import path

from .views import OrderCreateView, OrderDetailView

app_name = "order"

urlpatterns = [
    path("create/", OrderCreateView.as_view(), name="order_create"),
    path("<int:pk>", OrderDetailView.as_view(), name="order_detail"),
]

myshop/products/urls.py
from django.urls import path

from .views import ProductListView, ProductDetailView

app_name = "products"

urlpatterns = [
    path("", ProductListView.as_view(), name="products_list"),
    path(
        "<slug:category_slug>/",
        ProductListView.as_view(),
        name="products_list_by_category",
    ),
    path(
        "<int:pk>/<slug:slug>/",
        ProductDetailView.as_view(),
        name="product_detail",
    ),
]

myshop/cart/models.py
from django.db import models

# Create your models here.

myshop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    """
    TODO
    """

    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int,
        widget=forms.Select(attrs={"class": "form-select"}),
    )
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

myshop/cart/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from products.models import Product
from .cart import Cart
from .forms import CartAddProductForm


def get_request_cart_data(request, product_pk):
    """
    TODO
    """
    cart = Cart(request)
    product = get_object_or_404(Product, pk=product_pk)
    return cart, product


@login_required
@require_POST
def cart_add(request, product_pk):
    """
    TODO
    """
    cart, product = get_request_cart_data(request, product_pk)
    form = CartAddProductForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product,
            quantity=cd["quantity"],
            update_quantity=cd["update"],
        )

    return redirect("cart:cart_detail")


@login_required
def cart_remove(request, product_pk):
    """
    TODO
    """
    cart, product = get_request_cart_data(request, product_pk)
    cart.remove(product)
    return redirect("cart:cart_detail")


@login_required
def cart_detail(request):
    """
    TODO
    """
    cart = Cart(request)
    return render(request, "cart/cart_detail.html", {"cart": cart})

myshop/cart/templates/cart/cart_detail.html
{% extends 'base.html' %}

{% load static %}
{% load bootstrap_icons %}

{% block head %}
  <link rel="stylesheet" href="{% static "products/css/index.css" %}">
{% endblock %}

{% block title %}
  Cart
{% endblock %}

{% block container %}
  <div class="container">
    {% if cart %}
      <h3 class="my-3">Your shopping cart</h3>
      <table class="table table-striped table-hover text-center">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Product</th>
            <th scope="col">Quantity</th>
            <th scope="col"></th>
            <th scope="col">Unit price</th>
            <th scope="col">Price</th>
          </tr>
        </thead>
        <tbody>
          {% for item in cart %}
            {% with item.product as product %}
              <tr>
                <td>
                  <a href="{% url 'products:product_detail' product.id product.slug %}">
                      <img
                        src="{% if product.image %}
                              {{ product.image.url }}
                              {% else %}
                                {% static 'img/no-image.png' %}
                              {% endif %}"
                        class='card-img-top product-image'
                        alt='no image'
                      >
                    </a>
                </td>
                <td>
                  {{ product.name }}
                </td>
                <td>
                  {{ item.quantity }}
                </td>
                <td>
                  <a href="{% url 'cart:cart_remove' product.pk %}">
                    {% bs_icon 'trash3' color='red' %}
                  </a>
                </td>
                <td>
                  ${{ item.price }}
                </td>
                <td>
                  ${{ item.total_price }}
                </td>
              </tr>
            {% endwith %}
          {% endfor %}
          <tr class="table-success">
            <td>Total</td>
            <td colspan="4"></td>
            <td>${{ cart.get_total_price }}</td>
          </tr>
        </tbody>
      </table>
    {% else %}
      <h3 class="my-5 text-center">Your shopping cart is empty...</h3>
    {% endif %}
    <div class="d-flex flex-row justify-content-center">
      <a class="btn btn-primary" href="{% url 'products:products_list' %}">Continue shopping</a>
      {% if cart %}
        <a class='btn btn-success ms-2' href="{% url 'order:order_create' %}">Checkout</a>
      {% endif %}
    </div>
  </div>
{% endblock %}