myshop/cart/urls.py
from django.urls import path

from .views import cart_remove, cart_add, cart_detail

app_name = "cart"

urlpatterns = [
    path("", cart_detail, name="cart_detail"),
    path(
        "add/<int:product_pk>",
        cart_add,
        name="cart_add",
    ),
    path(
        "remove/<int:product_pk>",
        cart_remove,
        name="cart_remove",
    ),
]

myshop/myshop/urls.py
import pkgutil

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("cart/", include("cart.urls")),
    path("order/", include("order.urls")),
    path("myauth/", include("myauth.urls")),
    path("", include("products.urls")),
]

if settings.DEBUG and pkgutil.find_loader("debug_toolbar"):
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/products/urls.py
from django.urls import path

from .views import ProductListView, ProductDetailView

app_name = "products"

urlpatterns = [
    path("", ProductListView.as_view(), name="products_list"),
    path(
        "<slug:category_slug>/",
        ProductListView.as_view(),
        name="products_list_by_category",
    ),
    path(
        "<int:pk>/<slug:slug>/",
        ProductDetailView.as_view(),
        name="product_detail",
    ),
]

myshop/products/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    """
    TODO
    """

    name = models.CharField(max_length=128, db_index=True)
    slug = models.SlugField(max_length=128, db_index=True, unique=True)
    description = models.CharField(max_length=512, blank=True)

    class Meta:
        ordering = ("name",)
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse(
            "products:products_list_by_category",
            args=[self.slug],
        )


class Product(models.Model):
    """
    TODO
    """

    name = models.CharField(max_length=128, db_index=True)
    slug = models.SlugField(max_length=128, db_index=True)
    category = models.ForeignKey(
        Category, related_name="products", on_delete=models.PROTECT
    )
    image = models.ImageField(upload_to="products/%Y/%m/%d", blank=True)
    description = models.CharField(max_length=512, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("name",)
        index_together = (("id", "slug"),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """
        TODO
        """
        return reverse(
            "products:product_detail",
            args=[self.pk, self.slug],
        )

myshop/products/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.views import generic

from cart.forms import CartAddProductForm
from .models import Product, Category


class ProductListView(LoginRequiredMixin, generic.ListView):
    """
    TODO
    """

    model = Product
    template_name = "product_list.html"
    ordering = ("name",)
    context_object_name = "product_list"

    def get_queryset(self):
        """
        TODO
        """
        return Product.objects.filter(available=True)

    def get_context_data(self, **kwargs):
        """
        TODO
        """
        category_slug = self.kwargs.get("category_slug")
        category = None
        context = super(ProductListView, self).get_context_data(**kwargs)

        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            if category:
                product_list = Product.objects.filter(available=True, category=category)
                context["product_list"] = product_list

        context["category"] = category
        context["categories"] = Category.objects.all()

        return context


class ProductDetailView(LoginRequiredMixin, generic.DetailView):
    """
    TODO
    """

    model = Product
    template_name = "products/product_detail.html"
    context_object_name = "product"

    def get_context_data(self, **kwargs):
        """
        TODO
        """
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        cart_form = CartAddProductForm()
        context["cart_product_form"] = cart_form
        return context

myshop/products/templates/products/category_sidebar.html
<div class="list-group">
  {% for category_elem in categories %}
    <li
      class="list-group-item d-flex justify-content-between align-items-center
        {% if category_elem == category %}
          active
        {% endif %}"
    >
      <a class="{% if category_elem == category %}
                  link-light
                {% else %}
                  link-dark
                {% endif %}"
         href="{{ category_elem.get_absolute_url }}">
        {{ category_elem }}
      </a>
      <span class="badge bg-info rounded-pill ms-5">0</span>
    </li>
  {% endfor %}
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <a class="link-dark" href="{% url 'products:products_list' %}">All</a>
  </li>
</div>

myshop/products/templates/products/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static "products/css/index.css" %}">
{% endblock %}

{% block title %}
  Product detail
{% endblock %}

{% block container %}
  <div class="container">
    <div class="card mb-3">
      <div class="row">
        <div class="col-md-4">
          <img src="{% if product.image %}
                    {{ product.image.url }}
                    {% else %}
                      {% static "img/no-image.png" %}
                    {% endif %}"
               class="img-fluid rounded-start product-image-lg"
               alt="no image">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <div class="d-flex justify-content-between">
              <h5 class="card-title">{{ product.name }}</h5>
              {% if product.stock < 3 %}
                <p class="card-text">
                  <span class="badge text-bg-danger ms-5">Only {{ product.stock }} in stock!</span>
                </p>
              {% endif %}
            </div>
            <div class="d-flex align-items-center justify-content-between mt-4">
              <h4 class="card-title">${{ product.price }}</h4>
              <form class="ms-5" action="{% url "cart:cart_add" product.id %}" method="post">
                  <div class="d-flex align-items-center">
                    {{ cart_product_form }}
                    <input type="submit" class="btn btn-success ms-2" value="Add to cart">
                  </div>
                  {% csrf_token %}
              </form>
            </div>
            <hr>
            <p class="card-text">{{ product.description }}</p>
            <div class="d-flex flex-column align-items-start mb-3 me-2">
              <a
                class="btn btn-primary"
                href="{% url "products:products_list" %}"
                role="button"
              >
                Continue shopping
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

myshop/products/templates/products/product_list.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static "products/css/index.css" %}">
{% endblock %}

{% block title %}
  Products
{% endblock %}

{% block container %}
  <div class="container d-flex">
    {% include "products/category_sidebar.html" %}
    <div class="vr mx-5"></div>
    <div class="container-fluid">
      <div class="row">
        {% for product in product_list %}
          <div class="col-md-auto">
            <div class="card">
              <div class="align-self-center">
                <a href="{% url 'products:product_detail' product.id product.slug %}">
                  <img
                    src="{% if product.image %}
                          {{ product.image.url }}
                          {% else %}
                            {% static "img/no-image.png" %}
                          {% endif %}"
                    class="card-img-top product-image"
                    alt="no image"
                  >
                </a>
              </div>
              <div class="card-body">
                <div class="d-flex justify-content-between align-items-center">
                  <a
                    class="text-decoration-none card-title"
                    href="{% url 'products:product_detail' product.id product.slug %}"
                  >{{ product.name }}</a>
                  {% if product.stock %}
                    <span class="badge bg-success rounded-pill ms-5">In stock!</span>
                  {% endif %} 
                </div>
                <h6 class="card-text">${{ product.price }}</h6>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}